FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Run the development server and expose it to other containers
CMD ["npm", "run", "dev", "--", "--host"]
