FROM node:22-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Expose the application port
EXPOSE 3000

# Run the development server with nodemon
CMD ["npm", "run", "dev"]
